---
assumable_roles: roles.cf
stack_name: Example-RoleModel
master_account_id: 123456789012
master_account_profile: dev
assumable_accounts:
  -
    name: prod
    profile: prod
  -
    name: cdn
    profile: cdn